spring.application.name=devcafe

spring.datasource.url=jdbc:h2:file:./database.db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
# Devolve a mensagem de erro dos Services para o front-end exibir.
server.error.include-message=always
